### ISSUE TITLE
修复楷体字体名称

### ISSUE THREAD

**Issue by RicoloveFeng** [SPGoding/spx#39]
中文楷体字体标签中的逗号被错误地修改为中文逗号。英文部分是正常的。

`[font=楷体,楷体_GB2312] -> [font=楷体，楷体_GB2312]`

这是一个低优先级的bug，可以考虑延后处理。

**Comment by SPGoding** [comment]
把逗号删掉就可以了对吧呐呐呐呐

**Comment by SPGoding** [comment]
破案了。
SPX 会把跟着空格或行末的逗号替换成全角，而我正好手欠地写了个 `[font=楷体, 楷体_GB2312]`。把空格删掉就好了。
