### ISSUE TITLE
地下城新闻被识别为每周快照

### ISSUE THREAD

**Issue by xz-cs** [SPGoding/spx#63]
刚刚去翻译了下[地下城新DLC发布的博文](https://www.minecraft.net/en-us/article/flames-nether-dlc-out-now)，但spx自动识别为了每周快照，并附带了新闻版快照模版。

**Comment by SPGoding** [comment]
[这里](https://github.com/SPGoding/spx/blob/fe96386f8a3667403b1cbacd87b572a6d4dd87aa/src/index.ts#L240-L246) 假设了所有 NEWS 分类的博文都是版本发布，以及当时的最新版本是个快照版本，所以就带上快照的模板了。

不知道怎么修，一个模板删掉就好，问题不大（
